# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EcoStore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EcoStore
    pod 'Alamofire', '~> 4.7'
    pod 'SwiftyJSON', '~> 4.0'
end
